#!/bin/sh

set -e

mkdir -p ~/Library/Application\ Support/Cells
mv /tmp/track_templates ~/Library/Application\ Support/Cells
chown -R $(stat -f "%Su" /dev/console) ~/Library/Application\ Support/Cells/

exit 0
