#!/bin/sh

set -e

cd $(dirname "$0")

mkdir -p $HOME/.local/share/Cells/
rm -rf $HOME/.local/share/Cells/track_templates
mv -f /tmp/track_templates $HOME/.local/share/Cells/
chown -R $(logname) $HOME/.local/share/Cells/track_templates/

exit 0
