#!/bin/sh

set -e

. ~/.bash_profile

cd $(dirname "$0")

export PYTHONPATH="$(pwd)/python/lib/python3.7/site-packages"
set PYTHONHOME="$(pwd)/python"
export PYTHONHOME="$(pwd)/python"
python/bin/python3 -m cells
